/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

/**
 *
 * @author DELL
 */
public class Display extends javax.swing.JFrame {
    /**
     * Creates new form mainUI
     */
    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        kButton8 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(53, 92, 125));
        kGradientPanel1.setkStartColor(new java.awt.Color(246, 114, 128));

        kButton1.setBorder(null);
        kButton1.setText("Perkalian");
        kButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(248, 177, 149));
        kButton1.setkBorderRadius(30);
        kButton1.setkEndColor(new java.awt.Color(248, 177, 149));
        kButton1.setkHoverEndColor(new java.awt.Color(246, 114, 128));
        kButton1.setkHoverForeGround(new java.awt.Color(248, 177, 149));
        kButton1.setkHoverStartColor(new java.awt.Color(192, 108, 132));
        kButton1.setkPressedColor(new java.awt.Color(246, 114, 128));
        kButton1.setkStartColor(new java.awt.Color(248, 177, 149));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setBorder(null);
        kButton2.setText("Pengurangan");
        kButton2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(248, 177, 149));
        kButton2.setkBorderRadius(30);
        kButton2.setkEndColor(new java.awt.Color(248, 177, 149));
        kButton2.setkHoverEndColor(new java.awt.Color(246, 114, 128));
        kButton2.setkHoverForeGround(new java.awt.Color(248, 177, 149));
        kButton2.setkHoverStartColor(new java.awt.Color(192, 108, 132));
        kButton2.setkPressedColor(new java.awt.Color(246, 114, 128));
        kButton2.setkStartColor(new java.awt.Color(248, 177, 149));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton3.setBorder(null);
        kButton3.setText("Penjumlahan");
        kButton3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(248, 177, 149));
        kButton3.setkBorderRadius(30);
        kButton3.setkEndColor(new java.awt.Color(248, 177, 149));
        kButton3.setkHoverEndColor(new java.awt.Color(246, 114, 128));
        kButton3.setkHoverForeGround(new java.awt.Color(248, 177, 149));
        kButton3.setkHoverStartColor(new java.awt.Color(192, 108, 132));
        kButton3.setkPressedColor(new java.awt.Color(246, 114, 128));
        kButton3.setkStartColor(new java.awt.Color(248, 177, 149));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        kButton4.setBorder(null);
        kButton4.setText("Pembagian");
        kButton4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(248, 177, 149));
        kButton4.setkBorderRadius(30);
        kButton4.setkEndColor(new java.awt.Color(248, 177, 149));
        kButton4.setkHoverEndColor(new java.awt.Color(246, 114, 128));
        kButton4.setkHoverForeGround(new java.awt.Color(248, 177, 149));
        kButton4.setkHoverStartColor(new java.awt.Color(192, 108, 132));
        kButton4.setkPressedColor(new java.awt.Color(246, 114, 128));
        kButton4.setkStartColor(new java.awt.Color(248, 177, 149));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton5.setBorder(null);
        kButton5.setText("Faktorial");
        kButton5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        kButton5.setkBackGroundColor(new java.awt.Color(248, 177, 149));
        kButton5.setkBorderRadius(30);
        kButton5.setkEndColor(new java.awt.Color(248, 177, 149));
        kButton5.setkHoverEndColor(new java.awt.Color(246, 114, 128));
        kButton5.setkHoverForeGround(new java.awt.Color(248, 177, 149));
        kButton5.setkHoverStartColor(new java.awt.Color(192, 108, 132));
        kButton5.setkPressedColor(new java.awt.Color(246, 114, 128));
        kButton5.setkStartColor(new java.awt.Color(248, 177, 149));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        kButton6.setBorder(null);
        kButton6.setText("Modulo");
        kButton6.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(248, 177, 149));
        kButton6.setkBorderRadius(30);
        kButton6.setkEndColor(new java.awt.Color(248, 177, 149));
        kButton6.setkHoverEndColor(new java.awt.Color(246, 114, 128));
        kButton6.setkHoverForeGround(new java.awt.Color(248, 177, 149));
        kButton6.setkHoverStartColor(new java.awt.Color(192, 108, 132));
        kButton6.setkPressedColor(new java.awt.Color(246, 114, 128));
        kButton6.setkStartColor(new java.awt.Color(248, 177, 149));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        kButton7.setBorder(null);
        kButton7.setText("Pangkat");
        kButton7.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        kButton7.setkBackGroundColor(new java.awt.Color(248, 177, 149));
        kButton7.setkBorderRadius(30);
        kButton7.setkEndColor(new java.awt.Color(248, 177, 149));
        kButton7.setkHoverEndColor(new java.awt.Color(246, 114, 128));
        kButton7.setkHoverForeGround(new java.awt.Color(248, 177, 149));
        kButton7.setkHoverStartColor(new java.awt.Color(192, 108, 132));
        kButton7.setkPressedColor(new java.awt.Color(246, 114, 128));
        kButton7.setkStartColor(new java.awt.Color(248, 177, 149));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });

        kButton8.setBorder(null);
        kButton8.setText("Log Biner");
        kButton8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        kButton8.setkBackGroundColor(new java.awt.Color(248, 177, 149));
        kButton8.setkBorderRadius(30);
        kButton8.setkEndColor(new java.awt.Color(248, 177, 149));
        kButton8.setkHoverEndColor(new java.awt.Color(246, 114, 128));
        kButton8.setkHoverForeGround(new java.awt.Color(248, 177, 149));
        kButton8.setkHoverStartColor(new java.awt.Color(192, 108, 132));
        kButton8.setkPressedColor(new java.awt.Color(246, 114, 128));
        kButton8.setkStartColor(new java.awt.Color(248, 177, 149));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("- Simulator -");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 177, 149));
        jLabel2.setText("MACHINE");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("TURING");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton8ActionPerformed

    public static void display() {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
